version: "3"
services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "3232:3232"
    container_name: go_api
    depends_on:
      - mongo

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: nextjs_web
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
